CREATE DATABASE employee;
USE employee;
CREATE TABLE EMPLOYEES(
ID INT PRIMARY KEY,
Name VARCHAR(50),
Salary INT NOT NULL
);
INSERT INTO EMPLOYEES (ID,Name,salary)
VALUES
(01,"Adam",25000),
(02,"Bob",30000),
(03,"Casey",40000);
SELECT * FROM EMPLOYEES;
